# Generated by Django 6.0.8 on 2026-08-29 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_loginpage_registerpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginpage',
            name='register_link_text',
            field=models.CharField(blank=True, default='Register', max_length=50),
        ),
        migrations.AddField(
            model_name='loginpage',
            name='register_prompt_text',
            field=models.CharField(blank=True, default="Don't have an account?", max_length=100),
        ),
        migrations.AddField(
            model_name='loginpage',
            name='submit_button_text',
            field=models.CharField(blank=True, default='Login', max_length=50),
        ),
        migrations.AddField(
            model_name='registerpage',
            name='confirm_password_label',
            field=models.CharField(blank=True, default='Confirm Password', max_length=50),
        ),
        migrations.AddField(
            model_name='registerpage',
            name='email_label',
            field=models.CharField(blank=True, default='Email address', max_length=50),
        ),
        migrations.AddField(
            model_name='registerpage',
            name='first_name_label',
            field=models.CharField(blank=True, default='First Name', max_length=50),
        ),
        migrations.AddField(
            model_name='registerpage',
            name='last_name_label',
            field=models.CharField(blank=True, default='Last Name', max_length=50),
        ),
        migrations.AddField(
            model_name='registerpage',
            name='login_link_text',
            field=models.CharField(blank=True, default='Login', max_length=50),
        ),
        migrations.AddField(
            model_name='registerpage',
            name='login_prompt_text',
            field=models.CharField(blank=True, default='Already have an account?', max_length=100),
        ),
        migrations.AddField(
            model_name='registerpage',
            name='password_label',
            field=models.CharField(blank=True, default='Password', max_length=50),
        ),
        migrations.AddField(
            model_name='registerpage',
            name='role_label',
            field=models.CharField(blank=True, default='Role', max_length=50),
        ),
        migrations.AddField(
            model_name='registerpage',
            name='submit_button_text',
            field=models.CharField(blank=True, default='Register', max_length=50),
        ),
    ]
