# Generated by Django 6.0.8 on 2026-09-01 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_loginpage_register_link_text_and_more'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDashboardPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('welcome_heading', models.CharField(blank=True, default='Welcome back', max_length=150)),
                ('welcome_subtext', models.CharField(blank=True, default='Manage your assigned blogs, workspace, and publish content seamlessly.', max_length=255)),
                ('cms_button_text', models.CharField(blank=True, default='Open Wagtail CMS', max_length=50)),
            ],
            options={
                'verbose_name': 'User Dashboard Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
