# Generated by Django 6.0.8 on 2026-09-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userdashboardpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdashboardpage',
            name='brand_name',
            field=models.CharField(blank=True, default='InsightCMS', max_length=100),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='logout_text',
            field=models.CharField(blank=True, default='Logout', max_length=50),
        ),
    ]
