# Generated by Django 6.0.8 on 2026-09-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userdashboardpage_brand_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('editor', 'Editor'), ('manager', 'Manager')], default='editor', max_length=20, verbose_name='Role'),
        ),
    ]
