# Generated by Django 6.0.8 on 2026-09-02 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdashboardpage',
            name='cms_button_text',
        ),
        migrations.RemoveField(
            model_name='userdashboardpage',
            name='logout_text',
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='footer_tagline',
            field=models.TextField(blank=True, default='The all-in-one blogging platform that helps you create, manage, and grow your blog.'),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='nav_analytics_text',
            field=models.CharField(blank=True, default='Analytics', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='nav_appearance_text',
            field=models.CharField(blank=True, default='Appearance', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='nav_categories_text',
            field=models.CharField(blank=True, default='Categories', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='nav_comments_badge',
            field=models.CharField(blank=True, default='24', max_length=20),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='nav_comments_text',
            field=models.CharField(blank=True, default='Comments', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='nav_dashboard_text',
            field=models.CharField(blank=True, default='Dashboard', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='nav_media_text',
            field=models.CharField(blank=True, default='Media', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='nav_pages_text',
            field=models.CharField(blank=True, default='Pages', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='nav_plugins_text',
            field=models.CharField(blank=True, default='Plugins', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='nav_posts_text',
            field=models.CharField(blank=True, default='Posts', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='nav_preferences_heading',
            field=models.CharField(blank=True, default='PREFERENCES', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='nav_settings_text',
            field=models.CharField(blank=True, default='Settings', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='nav_subscribers_text',
            field=models.CharField(blank=True, default='Subscribers', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='new_post_button_text',
            field=models.CharField(blank=True, default='+ New Post', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='newsletter_placeholder',
            field=models.CharField(blank=True, default='Enter your email', max_length=100),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='show_upgrade_banner',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='sidebar_upgrade_button_text',
            field=models.CharField(blank=True, default='Upgrade Now', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='sidebar_upgrade_text',
            field=models.CharField(blank=True, default='Unlock advanced features and grow your blog faster.', max_length=200),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='sidebar_upgrade_title',
            field=models.CharField(blank=True, default='Upgrade to Pro', max_length=100),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='stat_1_growth',
            field=models.CharField(blank=True, default='+ 12.5%', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='stat_1_label',
            field=models.CharField(blank=True, default='Total Posts', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='stat_1_value',
            field=models.CharField(blank=True, default='128', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='stat_2_growth',
            field=models.CharField(blank=True, default='+ 18.6%', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='stat_2_label',
            field=models.CharField(blank=True, default='Total Views', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='stat_2_value',
            field=models.CharField(blank=True, default='24.5K', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='stat_3_growth',
            field=models.CharField(blank=True, default='+ 8.2%', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='stat_3_label',
            field=models.CharField(blank=True, default='Comments', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='stat_3_value',
            field=models.CharField(blank=True, default='320', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='stat_4_growth',
            field=models.CharField(blank=True, default='+ 15.3%', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='stat_4_label',
            field=models.CharField(blank=True, default='Subscribers', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='stat_4_value',
            field=models.CharField(blank=True, default='1.2K', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='stat_5_growth',
            field=models.CharField(blank=True, default='+ 10.1%', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='stat_5_label',
            field=models.CharField(blank=True, default='Published Posts', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='stat_5_value',
            field=models.CharField(blank=True, default='98', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='upgrade_banner_button_text',
            field=models.CharField(blank=True, default='Upgrade Now', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='upgrade_banner_button_url',
            field=models.CharField(blank=True, default='#', max_length=255),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='upgrade_banner_text',
            field=models.CharField(blank=True, default='Upgrade to BlogPro Pro and unlock powerful features.', max_length=255),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='upgrade_banner_title',
            field=models.CharField(blank=True, default='Ready to take your blog to the next level?', max_length=200),
        ),
        migrations.AlterField(
            model_name='userdashboardpage',
            name='brand_name',
            field=models.CharField(blank=True, default='BlogPro', max_length=100),
        ),
        migrations.AlterField(
            model_name='userdashboardpage',
            name='welcome_heading',
            field=models.CharField(blank=True, default='Dashboard', max_length=150),
        ),
        migrations.AlterField(
            model_name='userdashboardpage',
            name='welcome_subtext',
            field=models.CharField(blank=True, default="Welcome back! Here's what's happening with your blog.", max_length=255),
        ),
    ]
