# Generated by Django 6.0.8 on 2026-09-02 18:14

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_userdashboardpage_cms_button_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdashboardpage',
            name='nav_analytics_text',
        ),
        migrations.RemoveField(
            model_name='userdashboardpage',
            name='nav_appearance_text',
        ),
        migrations.RemoveField(
            model_name='userdashboardpage',
            name='nav_categories_text',
        ),
        migrations.RemoveField(
            model_name='userdashboardpage',
            name='nav_comments_badge',
        ),
        migrations.RemoveField(
            model_name='userdashboardpage',
            name='nav_comments_text',
        ),
        migrations.RemoveField(
            model_name='userdashboardpage',
            name='nav_dashboard_text',
        ),
        migrations.RemoveField(
            model_name='userdashboardpage',
            name='nav_media_text',
        ),
        migrations.RemoveField(
            model_name='userdashboardpage',
            name='nav_pages_text',
        ),
        migrations.RemoveField(
            model_name='userdashboardpage',
            name='nav_plugins_text',
        ),
        migrations.RemoveField(
            model_name='userdashboardpage',
            name='nav_posts_text',
        ),
        migrations.RemoveField(
            model_name='userdashboardpage',
            name='nav_preferences_heading',
        ),
        migrations.RemoveField(
            model_name='userdashboardpage',
            name='nav_settings_text',
        ),
        migrations.RemoveField(
            model_name='userdashboardpage',
            name='nav_subscribers_text',
        ),
        migrations.RemoveField(
            model_name='userdashboardpage',
            name='stat_1_growth',
        ),
        migrations.RemoveField(
            model_name='userdashboardpage',
            name='stat_1_label',
        ),
        migrations.RemoveField(
            model_name='userdashboardpage',
            name='stat_1_value',
        ),
        migrations.RemoveField(
            model_name='userdashboardpage',
            name='stat_2_growth',
        ),
        migrations.RemoveField(
            model_name='userdashboardpage',
            name='stat_2_label',
        ),
        migrations.RemoveField(
            model_name='userdashboardpage',
            name='stat_2_value',
        ),
        migrations.RemoveField(
            model_name='userdashboardpage',
            name='stat_3_growth',
        ),
        migrations.RemoveField(
            model_name='userdashboardpage',
            name='stat_3_label',
        ),
        migrations.RemoveField(
            model_name='userdashboardpage',
            name='stat_3_value',
        ),
        migrations.RemoveField(
            model_name='userdashboardpage',
            name='stat_4_growth',
        ),
        migrations.RemoveField(
            model_name='userdashboardpage',
            name='stat_4_label',
        ),
        migrations.RemoveField(
            model_name='userdashboardpage',
            name='stat_4_value',
        ),
        migrations.RemoveField(
            model_name='userdashboardpage',
            name='stat_5_growth',
        ),
        migrations.RemoveField(
            model_name='userdashboardpage',
            name='stat_5_label',
        ),
        migrations.RemoveField(
            model_name='userdashboardpage',
            name='stat_5_value',
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='copyright_text',
            field=models.CharField(blank=True, default='© 2024 BlogPro. All rights reserved.', max_length=255),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='new_post_button_url',
            field=models.CharField(blank=True, default='/cms/pages/', max_length=255),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='notification_count',
            field=models.CharField(blank=True, default='3', max_length=10),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='privacy_policy_text',
            field=models.CharField(blank=True, default='Privacy Policy ›', max_length=100),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='privacy_policy_url',
            field=models.CharField(blank=True, default='#', max_length=255),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='search_placeholder',
            field=models.CharField(blank=True, default='Search anything...', max_length=100),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='search_shortcut',
            field=models.CharField(blank=True, default='⌘K', max_length=20),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='sidebar_links',
            field=wagtail.fields.StreamField([('link', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Posts', 'help_text': 'Link name (e.g. Posts, Categories, Media)', 'max_length': 50, 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'default': '/cms/pages/', 'help_text': 'URL path (e.g. /dashboard/, /cms/pages/)', 'max_length': 255, 'required': True}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('fa-table-cells-large', 'Dashboard / Grid'), ('fa-pen-nib', 'Pen / Posts'), ('fa-layer-group', 'Layer / Categories'), ('fa-image', 'Image / Media'), ('fa-file-lines', 'File / Pages'), ('fa-comments', 'Comments'), ('fa-chart-line', 'Chart / Analytics'), ('fa-user', 'User / Subscribers'), ('fa-wand-magic-sparkles', 'Magic / Appearance'), ('fa-puzzle-piece', 'Puzzle / Plugins'), ('fa-gear', 'Gear / Settings')], 'help_text': 'Choose FontAwesome Icon'}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional badge text (e.g. 24 or New)', 'max_length': 10, 'required': False}), 4: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Highlight as active/selected item', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('url', 1), ('icon', 2), ('badge_text', 3), ('is_active', 4)]], {})}, help_text='Dynamic Sidebar Navigation Links'),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='stat_cards',
            field=wagtail.fields.StreamField([('stat', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Total Posts', 'max_length': 50, 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'default': '128', 'max_length': 50, 'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'default': '+ 12.5%', 'help_text': 'e.g. + 12.5%', 'max_length': 50, 'required': False}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('icon-blue', 'Blue (Posts)'), ('icon-cyan', 'Cyan (Views)'), ('icon-pink', 'Pink (Comments)'), ('icon-purple', 'Purple (Subscribers)'), ('icon-orange', 'Orange (Published)')]}), 4: ('wagtail.blocks.StructBlock', [[('label', 0), ('value', 1), ('growth', 2), ('icon_theme', 3)]], {})}, help_text='Top Stat Cards (Total Posts, Views, Comments, etc.)'),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='terms_service_text',
            field=models.CharField(blank=True, default='Terms of Service ›', max_length=100),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='terms_service_url',
            field=models.CharField(blank=True, default='#', max_length=255),
        ),
    ]
