# Generated by Django 6.0.8 on 2026-09-03 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_userdashboardpage_nav_analytics_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdashboardpage',
            name='action_1_desc',
            field=models.CharField(blank=True, default='Create and publish article', max_length=150),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='action_1_title',
            field=models.CharField(blank=True, default='Write New Post', max_length=100),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='action_1_url',
            field=models.CharField(blank=True, default='/cms/pages/', max_length=255),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='action_2_desc',
            field=models.CharField(blank=True, default='Add images and files', max_length=150),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='action_2_title',
            field=models.CharField(blank=True, default='Upload Media', max_length=100),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='action_2_url',
            field=models.CharField(blank=True, default='/cms/images/', max_length=255),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='action_3_desc',
            field=models.CharField(blank=True, default='Organize your content', max_length=150),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='action_3_title',
            field=models.CharField(blank=True, default='Add Category', max_length=100),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='action_3_url',
            field=models.CharField(blank=True, default='/cms/', max_length=255),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='action_4_desc',
            field=models.CharField(blank=True, default='Check detailed traffic stats', max_length=150),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='action_4_title',
            field=models.CharField(blank=True, default='View Analytics', max_length=100),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='action_4_url',
            field=models.CharField(blank=True, default='/dashboard/', max_length=255),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='audience_heading',
            field=models.CharField(blank=True, default='Audience Overview', max_length=150),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='audience_subtext',
            field=models.CharField(blank=True, default='Where your readers come from and how they browse', max_length=255),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='comments_heading',
            field=models.CharField(blank=True, default='Recent Comments', max_length=100),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='comments_subtext',
            field=models.CharField(blank=True, default='Latest reader interactions', max_length=150),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='countries_heading',
            field=models.CharField(blank=True, default='Top Countries', max_length=100),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='country_1_name',
            field=models.CharField(blank=True, default='United States', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='country_1_pct',
            field=models.CharField(blank=True, default='42%', max_length=10),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='country_2_name',
            field=models.CharField(blank=True, default='United Kingdom', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='country_2_pct',
            field=models.CharField(blank=True, default='18%', max_length=10),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='country_3_name',
            field=models.CharField(blank=True, default='Germany', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='country_3_pct',
            field=models.CharField(blank=True, default='12%', max_length=10),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='country_4_name',
            field=models.CharField(blank=True, default='India', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='country_4_pct',
            field=models.CharField(blank=True, default='9%', max_length=10),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='country_5_name',
            field=models.CharField(blank=True, default='Canada', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='country_5_pct',
            field=models.CharField(blank=True, default='6%', max_length=10),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='device_heading',
            field=models.CharField(blank=True, default='Device Types', max_length=100),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='quick_actions_heading',
            field=models.CharField(blank=True, default='Quick Actions', max_length=100),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='recent_posts_heading',
            field=models.CharField(blank=True, default='Recent Posts', max_length=150),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='recent_posts_subtext',
            field=models.CharField(blank=True, default='Manage your latest published and draft articles', max_length=255),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='storage_heading',
            field=models.CharField(blank=True, default='Storage Usage', max_length=100),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='storage_percent',
            field=models.CharField(blank=True, default='68%', max_length=20),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='storage_plan_name',
            field=models.CharField(blank=True, default='Free Plan', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='storage_used_text',
            field=models.CharField(blank=True, default='3.4 GB of 5 GB used', max_length=100),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='traffic_heading',
            field=models.CharField(blank=True, default='Traffic Sources', max_length=100),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='view_all_comments_text',
            field=models.CharField(blank=True, default='View All', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='view_all_comments_url',
            field=models.CharField(blank=True, default='/cms/', max_length=255),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='view_all_posts_text',
            field=models.CharField(blank=True, default='View All', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='view_all_posts_url',
            field=models.CharField(blank=True, default='/cms/pages/', max_length=255),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='views_chart_heading',
            field=models.CharField(blank=True, default='Views Overview', max_length=150),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='views_chart_subtext',
            field=models.CharField(blank=True, default='Daily visitors over the last 30 days', max_length=255),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='views_filter_1',
            field=models.CharField(blank=True, default='30 Days', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='views_filter_2',
            field=models.CharField(blank=True, default='7 Days', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='views_filter_3',
            field=models.CharField(blank=True, default='All Time', max_length=50),
        ),
    ]
