# Generated by Django 6.0.8 on 2026-09-03 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userdashboardpage_action_1_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdashboardpage',
            name='device_legend_1',
            field=models.CharField(blank=True, default='Desktop 60%', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='device_legend_2',
            field=models.CharField(blank=True, default='Mobile 35%', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='th_actions',
            field=models.CharField(blank=True, default='ACTIONS', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='th_category',
            field=models.CharField(blank=True, default='CATEGORY', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='th_date',
            field=models.CharField(blank=True, default='DATE', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='th_post_title',
            field=models.CharField(blank=True, default='POST TITLE', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='th_status',
            field=models.CharField(blank=True, default='STATUS', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='th_views',
            field=models.CharField(blank=True, default='VIEWS', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='traffic_legend_1',
            field=models.CharField(blank=True, default='Organic 60%', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='traffic_legend_2',
            field=models.CharField(blank=True, default='Social 20%', max_length=50),
        ),
    ]
