# Generated by Django 6.0.8 on 2026-09-03 04:32

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_userdashboardpage_device_legend_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdashboardpage',
            name='stat1_growth',
            field=models.CharField(blank=True, default='12.5%', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='stat1_label',
            field=models.CharField(blank=True, default='Total Posts', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='stat1_value',
            field=models.CharField(blank=True, default='128', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='stat2_growth',
            field=models.CharField(blank=True, default='18.6%', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='stat2_label',
            field=models.CharField(blank=True, default='Total Views', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='stat2_value',
            field=models.CharField(blank=True, default='24.5K', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='stat3_growth',
            field=models.CharField(blank=True, default='8.2%', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='stat3_label',
            field=models.CharField(blank=True, default='Comments', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='stat3_value',
            field=models.CharField(blank=True, default='320', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='stat4_growth',
            field=models.CharField(blank=True, default='15.3%', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='stat4_label',
            field=models.CharField(blank=True, default='Subscribers', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='stat4_value',
            field=models.CharField(blank=True, default='1.2K', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='stat5_growth',
            field=models.CharField(blank=True, default='10.1%', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='stat5_label',
            field=models.CharField(blank=True, default='Published Posts', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='stat5_value',
            field=models.CharField(blank=True, default='98', max_length=50),
        ),
        migrations.AlterField(
            model_name='userdashboardpage',
            name='stat_cards',
            field=wagtail.fields.StreamField([('stat', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Total Posts', 'max_length': 50, 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'default': '128', 'max_length': 50, 'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'default': '+ 12.5%', 'help_text': 'e.g. + 12.5%', 'max_length': 50, 'required': False}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('icon-blue', 'Blue (Posts)'), ('icon-cyan', 'Cyan (Views)'), ('icon-pink', 'Pink (Comments)'), ('icon-purple', 'Purple (Subscribers)'), ('icon-orange', 'Orange (Published)')]}), 4: ('wagtail.blocks.StructBlock', [[('label', 0), ('value', 1), ('growth', 2), ('icon_theme', 3)]], {})}, help_text='Top Stat Cards (Optional StreamField)'),
        ),
    ]
