# Generated by Django 6.0.8 on 2026-09-03 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_userdashboardpage_stat1_growth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdashboardpage',
            name='stat_caption',
            field=models.CharField(blank=True, default='vs last month', max_length=50),
        ),
    ]
