# Generated by Django 6.0.8 on 2026-09-03 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_userdashboardpage_stat_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdashboardpage',
            name='comment_1_author',
            field=models.CharField(blank=True, default='Alex Johnson', max_length=100),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='comment_1_post',
            field=models.CharField(blank=True, default='Getting Started with Wagtail CMS', max_length=150),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='comment_1_text',
            field=models.TextField(blank=True, default='Great insights on Wagtail StreamFields! Really helped my team configure modular pages.'),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='comment_1_time',
            field=models.CharField(blank=True, default='10m ago', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='comment_2_author',
            field=models.CharField(blank=True, default='Sarah Miller', max_length=100),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='comment_2_post',
            field=models.CharField(blank=True, default='10 Tips for Better Web Performance', max_length=150),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='comment_2_text',
            field=models.TextField(blank=True, default='Could you cover custom block migrations in the next tutorial? Highly requested!'),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='comment_2_time',
            field=models.CharField(blank=True, default='2h ago', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='comment_3_author',
            field=models.CharField(blank=True, default='David Lee', max_length=100),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='comment_3_post',
            field=models.CharField(blank=True, default='The Future of AI in Blogging', max_length=150),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='comment_3_text',
            field=models.TextField(blank=True, default='Clean layout and great responsiveness on mobile devices. Well done!'),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='comment_3_time',
            field=models.CharField(blank=True, default='1d ago', max_length=50),
        ),
    ]
