# Generated by Django 6.0.8 on 2026-09-03 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_userdashboardpage_comment_1_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdashboardpage',
            name='footer_col1_heading',
            field=models.CharField(blank=True, default='PRODUCT', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='footer_col1_link1_text',
            field=models.CharField(blank=True, default='Features', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='footer_col1_link1_url',
            field=models.CharField(blank=True, default='#', max_length=255),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='footer_col1_link2_text',
            field=models.CharField(blank=True, default='Pricing', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='footer_col1_link2_url',
            field=models.CharField(blank=True, default='#', max_length=255),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='footer_col1_link3_text',
            field=models.CharField(blank=True, default='Blog', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='footer_col1_link3_url',
            field=models.CharField(blank=True, default='#', max_length=255),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='footer_col1_link4_text',
            field=models.CharField(blank=True, default='Updates', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='footer_col1_link4_url',
            field=models.CharField(blank=True, default='#', max_length=255),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='footer_col2_heading',
            field=models.CharField(blank=True, default='SUPPORT', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='footer_col2_link1_text',
            field=models.CharField(blank=True, default='Help Center', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='footer_col2_link1_url',
            field=models.CharField(blank=True, default='#', max_length=255),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='footer_col2_link2_text',
            field=models.CharField(blank=True, default='Documentation', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='footer_col2_link2_url',
            field=models.CharField(blank=True, default='#', max_length=255),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='footer_col2_link3_text',
            field=models.CharField(blank=True, default='Contact Us', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='footer_col2_link3_url',
            field=models.CharField(blank=True, default='#', max_length=255),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='footer_col2_link4_text',
            field=models.CharField(blank=True, default='Community', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='footer_col2_link4_url',
            field=models.CharField(blank=True, default='#', max_length=255),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='footer_col3_heading',
            field=models.CharField(blank=True, default='COMPANY', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='footer_col3_link1_text',
            field=models.CharField(blank=True, default='About Us', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='footer_col3_link1_url',
            field=models.CharField(blank=True, default='#', max_length=255),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='footer_col3_link2_text',
            field=models.CharField(blank=True, default='Careers', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='footer_col3_link2_url',
            field=models.CharField(blank=True, default='#', max_length=255),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='footer_col3_link3_text',
            field=models.CharField(blank=True, default='Privacy Policy', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='footer_col3_link3_url',
            field=models.CharField(blank=True, default='#', max_length=255),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='footer_col3_link4_text',
            field=models.CharField(blank=True, default='Terms of Service', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='footer_col3_link4_url',
            field=models.CharField(blank=True, default='#', max_length=255),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='footer_facebook_url',
            field=models.CharField(blank=True, default='#', max_length=255),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='footer_instagram_url',
            field=models.CharField(blank=True, default='#', max_length=255),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='footer_linkedin_url',
            field=models.CharField(blank=True, default='#', max_length=255),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='footer_twitter_url',
            field=models.CharField(blank=True, default='#', max_length=255),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='newsletter_heading',
            field=models.CharField(blank=True, default='NEWSLETTER', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='newsletter_subtext',
            field=models.CharField(blank=True, default='Get the latest updates and tips for your blog.', max_length=150),
        ),
    ]
