# Generated by Django 6.0.8 on 2026-09-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_userdashboardpage_footer_col1_heading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdashboardpage',
            name='settings_notif_1_desc',
            field=models.CharField(blank=True, default='Get notified immediately whenever a reader leaves a comment on your posts.', max_length=255),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='settings_notif_1_title',
            field=models.CharField(blank=True, default='New Comments & Reader Interactions', max_length=150),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='settings_notif_2_desc',
            field=models.CharField(blank=True, default="Receive a weekly summary of your blog's visitors, top posts, and subscriber growth.", max_length=255),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='settings_notif_2_title',
            field=models.CharField(blank=True, default='Weekly Analytics Digest', max_length=150),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='settings_notif_3_desc',
            field=models.CharField(blank=True, default='Important updates about your account security and CMS updates.', max_length=255),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='settings_notif_3_title',
            field=models.CharField(blank=True, default='System & Security Alerts', max_length=150),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='settings_notif_btn_text',
            field=models.CharField(blank=True, default='Save Preferences', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='settings_notif_heading',
            field=models.CharField(blank=True, default='Notification Preferences', max_length=100),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='settings_notif_subtext',
            field=models.CharField(blank=True, default='Choose when and how you want to be notified about blog activities.', max_length=255),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='settings_page_subtext',
            field=models.CharField(blank=True, default='Manage your account preferences, workspace, and security settings.', max_length=255),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='settings_page_title',
            field=models.CharField(blank=True, default='Settings', max_length=100),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='settings_profile_btn_text',
            field=models.CharField(blank=True, default='Save Changes', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='settings_profile_heading',
            field=models.CharField(blank=True, default='Profile Information', max_length=100),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='settings_profile_subtext',
            field=models.CharField(blank=True, default='Update your personal details and public profile presence.', max_length=255),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='settings_security_badge_text',
            field=models.CharField(blank=True, default='Account Protected', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='settings_security_btn_text',
            field=models.CharField(blank=True, default='Update Password', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='settings_security_heading',
            field=models.CharField(blank=True, default='Security & Authentication', max_length=100),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='settings_security_subtext',
            field=models.CharField(blank=True, default='Manage your password, login security, and active sessions.', max_length=255),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='settings_session_desc',
            field=models.CharField(blank=True, default='Currently signed in from this browser.', max_length=255),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='settings_session_title',
            field=models.CharField(blank=True, default='Active Session', max_length=100),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='settings_workspace_btn_text',
            field=models.CharField(blank=True, default='Save Workspace', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='settings_workspace_domain',
            field=models.CharField(blank=True, default='insightcms.local', max_length=100),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='settings_workspace_heading',
            field=models.CharField(blank=True, default='Workspace Details', max_length=100),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='settings_workspace_subtext',
            field=models.CharField(blank=True, default='Configure your blog workspace, public name, and publishing preferences.', max_length=255),
        ),
    ]
