# Generated by Django 6.0.8 on 2026-09-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_userdashboardpage_settings_notif_1_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdashboardpage',
            name='settings_tab_1_title',
            field=models.CharField(blank=True, default='Profile', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='settings_tab_2_title',
            field=models.CharField(blank=True, default='Workspace', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='settings_tab_3_title',
            field=models.CharField(blank=True, default='Notifications', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='settings_tab_4_title',
            field=models.CharField(blank=True, default='Security', max_length=50),
        ),
    ]
