# Generated by Django 6.0.8 on 2026-09-04 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_userdashboardpage_settings_tab_1_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdashboardpage',
            name='settings_profile_avatar_btn_text',
            field=models.CharField(blank=True, default='Change Avatar', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='settings_profile_email_hint',
            field=models.CharField(blank=True, default='Email address is managed by your system administrator.', max_length=255),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='settings_profile_email_label',
            field=models.CharField(blank=True, default='Email Address', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='settings_profile_fname_label',
            field=models.CharField(blank=True, default='First Name', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='settings_profile_lname_label',
            field=models.CharField(blank=True, default='Last Name', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='settings_profile_role_label',
            field=models.CharField(blank=True, default='Role', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='settings_sec_conf_pass_label',
            field=models.CharField(blank=True, default='Confirm New Password', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='settings_sec_conf_pass_ph',
            field=models.CharField(blank=True, default='Confirm new password', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='settings_sec_curr_pass_label',
            field=models.CharField(blank=True, default='Current Password', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='settings_sec_curr_pass_ph',
            field=models.CharField(blank=True, default='••••••••', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='settings_sec_new_pass_label',
            field=models.CharField(blank=True, default='New Password', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='settings_sec_new_pass_ph',
            field=models.CharField(blank=True, default='Enter new password', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='settings_sec_signout_btn_text',
            field=models.CharField(blank=True, default='Sign Out', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='settings_ws_brand_label',
            field=models.CharField(blank=True, default='Workspace / Brand Name', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='settings_ws_domain_label',
            field=models.CharField(blank=True, default='Primary Domain', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='settings_ws_lang_label',
            field=models.CharField(blank=True, default='Default Publishing Language', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='settings_ws_timezone_label',
            field=models.CharField(blank=True, default='Timezone', max_length=50),
        ),
    ]
