# Generated by Django 6.0.8 on 2026-09-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_userdashboardpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdashboardpage',
            name='empty_create_btn_text',
            field=models.CharField(blank=True, default='Create your first blog', max_length=50),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='empty_posts_text',
            field=models.CharField(blank=True, default='No blog posts found.', max_length=100),
        ),
    ]
