# Generated by Django 6.0.8 on 2026-09-11 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_userdashboardpage_empty_create_btn_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerpage',
            name='admin_username_label',
            field=models.CharField(blank=True, default='Admin/User Name', max_length=50),
        ),
        migrations.AddField(
            model_name='registerpage',
            name='company_name_label',
            field=models.CharField(blank=True, default='Company Name', max_length=50),
        ),
        migrations.AddField(
            model_name='registerpage',
            name='website_url_label',
            field=models.CharField(blank=True, default='Website URL', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='admin_username',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Admin/User Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Company Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='website_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Website URL'),
        ),
    ]
