# Generated by Django 6.0.8 on 2026-09-11 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_registerpage_admin_username_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('company_admin', 'Company Admin'), ('company_user', 'Company User')], default='company_user', max_length=20, verbose_name='Role'),
        ),
    ]
