# Generated by Django 6.0.8 on 2026-09-14 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_remove_userdashboardpage_settings_notif_1_desc_and_more'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('settings_page_title', models.CharField(blank=True, default='Settings', max_length=100)),
                ('settings_page_subtext', models.CharField(blank=True, default='Manage your account preferences, workspace, and security settings.', max_length=255)),
                ('settings_tab_1_title', models.CharField(blank=True, default='Profile', max_length=50)),
                ('settings_tab_4_title', models.CharField(blank=True, default='Security', max_length=50)),
                ('settings_tab_team_title', models.CharField(blank=True, default='Team Members', max_length=50)),
                ('settings_profile_heading', models.CharField(blank=True, default='Profile Information', max_length=100)),
                ('settings_profile_subtext', models.CharField(blank=True, default='Update your personal details and public profile presence.', max_length=255)),
                ('settings_profile_avatar_btn_text', models.CharField(blank=True, default='Change Avatar', max_length=50)),
                ('settings_profile_fname_label', models.CharField(blank=True, default='First Name', max_length=50)),
                ('settings_profile_lname_label', models.CharField(blank=True, default='Last Name', max_length=50)),
                ('settings_profile_email_label', models.CharField(blank=True, default='Email Address', max_length=50)),
                ('settings_profile_email_hint', models.CharField(blank=True, default='Email address is managed by your system administrator.', max_length=255)),
                ('settings_profile_role_label', models.CharField(blank=True, default='Role', max_length=50)),
                ('settings_profile_btn_text', models.CharField(blank=True, default='Save Changes', max_length=50)),
                ('settings_security_heading', models.CharField(blank=True, default='Security & Authentication', max_length=100)),
                ('settings_security_subtext', models.CharField(blank=True, default='Manage your password, login security, and active sessions.', max_length=255)),
                ('settings_sec_curr_pass_label', models.CharField(blank=True, default='Current Password', max_length=50)),
                ('settings_sec_curr_pass_ph', models.CharField(blank=True, default='••••••••', max_length=50)),
                ('settings_sec_new_pass_label', models.CharField(blank=True, default='New Password', max_length=50)),
                ('settings_sec_new_pass_ph', models.CharField(blank=True, default='Enter new password', max_length=50)),
                ('settings_sec_conf_pass_label', models.CharField(blank=True, default='Confirm New Password', max_length=50)),
                ('settings_sec_conf_pass_ph', models.CharField(blank=True, default='Confirm new password', max_length=50)),
                ('settings_security_badge_text', models.CharField(blank=True, default='Account Protected', max_length=50)),
                ('settings_security_btn_text', models.CharField(blank=True, default='Update Password', max_length=50)),
                ('settings_session_title', models.CharField(blank=True, default='Active Session', max_length=100)),
                ('settings_session_desc', models.CharField(blank=True, default='Currently signed in from this browser.', max_length=255)),
                ('settings_sec_signout_btn_text', models.CharField(blank=True, default='Sign Out', max_length=50)),
                ('team_add_heading', models.CharField(blank=True, default='Add New Team Member', max_length=100)),
                ('team_add_subtext', models.CharField(blank=True, default='Create a new Company User (Writer/Editor) for your company.', max_length=255)),
                ('team_list_heading', models.CharField(blank=True, default='Current Team Members', max_length=100)),
                ('team_list_subtext', models.CharField(blank=True, default="People with access to your company's blogs.", max_length=255)),
                ('team_add_btn_text', models.CharField(blank=True, default='Add Company User', max_length=50)),
            ],
            options={
                'verbose_name': 'Settings Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
