# Generated by Django 6.0.8 on 2026-09-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_settingspage'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingspage',
            name='team_email_label',
            field=models.CharField(blank=True, default='Email Address *', max_length=50),
        ),
        migrations.AddField(
            model_name='settingspage',
            name='team_email_ph',
            field=models.CharField(blank=True, default='writer@company.com', max_length=100),
        ),
        migrations.AddField(
            model_name='settingspage',
            name='team_empty_text',
            field=models.CharField(blank=True, default='No members found.', max_length=100),
        ),
        migrations.AddField(
            model_name='settingspage',
            name='team_fname_label',
            field=models.CharField(blank=True, default='First Name', max_length=50),
        ),
        migrations.AddField(
            model_name='settingspage',
            name='team_fname_ph',
            field=models.CharField(blank=True, default='e.g. Rahul', max_length=100),
        ),
        migrations.AddField(
            model_name='settingspage',
            name='team_lname_label',
            field=models.CharField(blank=True, default='Last Name', max_length=50),
        ),
        migrations.AddField(
            model_name='settingspage',
            name='team_lname_ph',
            field=models.CharField(blank=True, default='e.g. Sharma', max_length=100),
        ),
        migrations.AddField(
            model_name='settingspage',
            name='team_password_label',
            field=models.CharField(blank=True, default='Temporary Password *', max_length=50),
        ),
        migrations.AddField(
            model_name='settingspage',
            name='team_password_ph',
            field=models.CharField(blank=True, default='Minimum 6 characters', max_length=100),
        ),
        migrations.AddField(
            model_name='settingspage',
            name='team_status_active_text',
            field=models.CharField(blank=True, default='Active', max_length=50),
        ),
        migrations.AddField(
            model_name='settingspage',
            name='team_th_email',
            field=models.CharField(blank=True, default='Email', max_length=50),
        ),
        migrations.AddField(
            model_name='settingspage',
            name='team_th_role',
            field=models.CharField(blank=True, default='Role', max_length=50),
        ),
        migrations.AddField(
            model_name='settingspage',
            name='team_th_status',
            field=models.CharField(blank=True, default='Status', max_length=50),
        ),
        migrations.AddField(
            model_name='settingspage',
            name='team_th_user',
            field=models.CharField(blank=True, default='User', max_length=50),
        ),
    ]
