# Generated by Django 6.0.8 on 2026-09-29 08:55

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_usernotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdashboardpage',
            name='comments_page_empty_heading',
            field=models.CharField(blank=True, default='No comments yet', max_length=100, verbose_name='Empty State Title'),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='comments_page_empty_subtext',
            field=models.CharField(blank=True, default='Visitor comments on your blog posts will appear here.', max_length=255, verbose_name='Empty State Subtitle'),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='comments_page_subtext',
            field=models.CharField(blank=True, default='Moderate visitor comments on your blog posts.', max_length=255, verbose_name='Comments Page Subtitle'),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='comments_page_title',
            field=models.CharField(blank=True, default='Comments', max_length=150, verbose_name='Comments Page Title'),
        ),
        migrations.AlterField(
            model_name='userdashboardpage',
            name='sidebar_links',
            field=wagtail.fields.StreamField([('link', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Posts', 'help_text': 'Link name (e.g. Posts, Categories, Media)', 'max_length': 50, 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'default': '/cms/pages/', 'help_text': 'URL path (e.g. /dashboard/, /cms/pages/)', 'max_length': 255, 'required': True}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('fa-table-cells-large', 'Dashboard / Grid'), ('fa-pen-nib', 'Pen / Posts'), ('fa-layer-group', 'Layer / Categories'), ('fa-image', 'Image / Media'), ('fa-file-lines', 'File / Pages'), ('fa-comments', 'Comments'), ('fa-chart-line', 'Chart / Analytics'), ('fa-user', 'User / Subscribers'), ('fa-user-gear', 'User / Profile Settings'), ('fa-wand-magic-sparkles', 'Magic / Appearance'), ('fa-puzzle-piece', 'Puzzle / Plugins'), ('fa-gear', 'Gear / Settings')], 'help_text': 'Choose FontAwesome Icon'}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional badge text (e.g. 24 or New)', 'max_length': 10, 'required': False}), 4: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Highlight as active/selected item', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('url', 1), ('icon', 2), ('badge_text', 3), ('is_active', 4)]], {})}, help_text='Dynamic Sidebar Navigation Links'),
        ),
    ]
