# Generated by Django 6.0.8 on 2026-09-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_userdashboardpage_comments_page_empty_heading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdashboardpage',
            name='comments_th_actions',
            field=models.CharField(blank=True, default='Actions', max_length=50, verbose_name='Column: Actions'),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='comments_th_author',
            field=models.CharField(blank=True, default='Author', max_length=50, verbose_name='Column: Author'),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='comments_th_comment',
            field=models.CharField(blank=True, default='Comment', max_length=50, verbose_name='Column: Comment'),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='comments_th_date',
            field=models.CharField(blank=True, default='Date', max_length=50, verbose_name='Column: Date'),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='comments_th_post',
            field=models.CharField(blank=True, default='Blog Post', max_length=50, verbose_name='Column: Blog Post'),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='comments_th_status',
            field=models.CharField(blank=True, default='Status', max_length=50, verbose_name='Column: Status'),
        ),
    ]
