# Generated by Django 6.0.8 on 2026-10-05 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_userdashboardpage_comments_th_actions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingspage',
            name='comments_setting_btn_text',
            field=models.CharField(blank=True, default='Save Comment Settings', max_length=50),
        ),
        migrations.AddField(
            model_name='settingspage',
            name='comments_setting_heading',
            field=models.CharField(blank=True, default='Blog Comments Configuration', max_length=100),
        ),
        migrations.AddField(
            model_name='settingspage',
            name='comments_setting_subtext',
            field=models.CharField(blank=True, default='Control comment settings globally across all blog posts.', max_length=255),
        ),
        migrations.AddField(
            model_name='settingspage',
            name='comments_setting_toggle_desc',
            field=models.CharField(blank=True, default='When enabled, visitors can post comments on your blogs. When disabled, comments are hidden globally.', max_length=255),
        ),
        migrations.AddField(
            model_name='settingspage',
            name='comments_setting_toggle_label',
            field=models.CharField(blank=True, default='Allow Comments on All Blogs', max_length=100),
        ),
        migrations.AddField(
            model_name='settingspage',
            name='settings_tab_comments_title',
            field=models.CharField(blank=True, default='Blog Comments', max_length=50),
        ),
    ]
