# Generated by Django 6.0.8 on 2026-10-07 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_settingspage_comments_setting_btn_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settingspage',
            name='comments_setting_toggle_desc',
        ),
        migrations.RemoveField(
            model_name='settingspage',
            name='comments_setting_toggle_label',
        ),
        migrations.AddField(
            model_name='settingspage',
            name='comments_email_mode_desc',
            field=models.CharField(blank=True, default='Choose whether Email is required, optional, or hidden.', max_length=255),
        ),
        migrations.AddField(
            model_name='settingspage',
            name='comments_email_mode_label',
            field=models.CharField(blank=True, default='Email Field Requirement', max_length=100),
        ),
        migrations.AddField(
            model_name='settingspage',
            name='comments_enable_desc',
            field=models.CharField(blank=True, default='Allow visitors to submit comments on blog posts.', max_length=255),
        ),
        migrations.AddField(
            model_name='settingspage',
            name='comments_enable_label',
            field=models.CharField(blank=True, default='Enable Comments', max_length=100),
        ),
        migrations.AddField(
            model_name='settingspage',
            name='comments_fields_heading',
            field=models.CharField(blank=True, default='Form Fields', max_length=100),
        ),
        migrations.AddField(
            model_name='settingspage',
            name='comments_fields_subtext',
            field=models.CharField(blank=True, default='Configure input requirements for comment submissions.', max_length=255),
        ),
        migrations.AddField(
            model_name='settingspage',
            name='comments_gen_heading',
            field=models.CharField(blank=True, default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='settingspage',
            name='comments_gen_subtext',
            field=models.CharField(blank=True, default='Configure core comment status, nested replies, and display limits.', max_length=255),
        ),
        migrations.AddField(
            model_name='settingspage',
            name='comments_mod_heading',
            field=models.CharField(blank=True, default='Moderation', max_length=100),
        ),
        migrations.AddField(
            model_name='settingspage',
            name='comments_mod_subtext',
            field=models.CharField(blank=True, default='Set automated review rules and visitor notices.', max_length=255),
        ),
        migrations.AddField(
            model_name='settingspage',
            name='comments_name_req_desc',
            field=models.CharField(blank=True, default='Visitor must enter their name to submit a comment.', max_length=255),
        ),
        migrations.AddField(
            model_name='settingspage',
            name='comments_name_req_label',
            field=models.CharField(blank=True, default='Name Field Required', max_length=100),
        ),
        migrations.AddField(
            model_name='settingspage',
            name='comments_per_page_desc',
            field=models.CharField(blank=True, default='Number of root comments loaded initially per post.', max_length=255),
        ),
        migrations.AddField(
            model_name='settingspage',
            name='comments_per_page_label',
            field=models.CharField(blank=True, default='Comments Per Page', max_length=100),
        ),
        migrations.AddField(
            model_name='settingspage',
            name='comments_replies_desc',
            field=models.CharField(blank=True, default='Allow users and staff to reply directly to existing comments.', max_length=255),
        ),
        migrations.AddField(
            model_name='settingspage',
            name='comments_replies_label',
            field=models.CharField(blank=True, default='Threaded Replies', max_length=100),
        ),
        migrations.AddField(
            model_name='settingspage',
            name='comments_review_all_desc',
            field=models.CharField(blank=True, default='When enabled, comments go to Pending queue until approved by Admin.', max_length=255),
        ),
        migrations.AddField(
            model_name='settingspage',
            name='comments_review_all_label',
            field=models.CharField(blank=True, default='Review All Comments', max_length=100),
        ),
        migrations.AddField(
            model_name='settingspage',
            name='comments_under_review_label',
            field=models.CharField(blank=True, default='Under-Review Notice Message', max_length=100),
        ),
        migrations.AddField(
            model_name='settingspage',
            name='comments_under_review_ph',
            field=models.CharField(blank=True, default='Your comment has been submitted and is awaiting approval.', max_length=255),
        ),
        migrations.AlterField(
            model_name='settingspage',
            name='comments_setting_heading',
            field=models.CharField(blank=True, default='Comments Settings', max_length=100),
        ),
        migrations.AlterField(
            model_name='settingspage',
            name='comments_setting_subtext',
            field=models.CharField(blank=True, default='Manage global blog comment behaviors, moderation policies, and submission form fields.', max_length=255),
        ),
    ]
