# Generated by Django 6.0.8 on 2026-10-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_remove_settingspage_comments_setting_toggle_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_blocked',
            field=models.BooleanField(default=False, verbose_name='Blocked by Admin'),
        ),
    ]
