# Generated by Django 6.0.8 on 2026-10-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_alter_userdashboardpage_sidebar_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingspage',
            name='manage_users_btn_add_text',
            field=models.CharField(blank=True, default='Add New User', max_length=50),
        ),
        migrations.AddField(
            model_name='settingspage',
            name='manage_users_card_heading',
            field=models.CharField(blank=True, default='Team Members', max_length=100),
        ),
        migrations.AddField(
            model_name='settingspage',
            name='manage_users_page_subtext',
            field=models.CharField(blank=True, default='Add team members, configure user permissions, and manage access.', max_length=255),
        ),
        migrations.AddField(
            model_name='settingspage',
            name='manage_users_page_title',
            field=models.CharField(blank=True, default='Manage User Settings', max_length=100),
        ),
        migrations.AddField(
            model_name='settingspage',
            name='manage_users_th_actions',
            field=models.CharField(blank=True, default='Actions', max_length=50),
        ),
        migrations.AddField(
            model_name='settingspage',
            name='manage_users_th_email',
            field=models.CharField(blank=True, default='Email', max_length=50),
        ),
        migrations.AddField(
            model_name='settingspage',
            name='manage_users_th_permissions',
            field=models.CharField(blank=True, default='Permissions', max_length=50),
        ),
        migrations.AddField(
            model_name='settingspage',
            name='manage_users_th_status',
            field=models.CharField(blank=True, default='Status', max_length=50),
        ),
        migrations.AddField(
            model_name='settingspage',
            name='manage_users_th_user',
            field=models.CharField(blank=True, default='User', max_length=50),
        ),
    ]
