# Generated by Django 6.0.8 on 2026-10-08 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_settingspage_manage_users_btn_add_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingspage',
            name='manage_users_tab_admins',
            field=models.CharField(blank=True, default='Administrators', max_length=50),
        ),
        migrations.AddField(
            model_name='settingspage',
            name='manage_users_tab_groups',
            field=models.CharField(blank=True, default='Groups', max_length=50),
        ),
        migrations.AddField(
            model_name='settingspage',
            name='manage_users_tab_users',
            field=models.CharField(blank=True, default='Users', max_length=50),
        ),
    ]
