# Generated by Django 6.0.8 on 2026-10-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_settingspage_manage_users_tab_admins_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingspage',
            name='integration_page_subtext',
            field=models.CharField(blank=True, default='Step-by-step instructions for integrating blogs on any website.', max_length=255),
        ),
        migrations.AddField(
            model_name='settingspage',
            name='integration_page_title',
            field=models.CharField(blank=True, default='Website Integration Guide', max_length=100),
        ),
        migrations.AddField(
            model_name='settingspage',
            name='integration_step1_title',
            field=models.CharField(blank=True, default='Your Live RSS Feed Endpoint', max_length=100),
        ),
        migrations.AddField(
            model_name='settingspage',
            name='integration_step2_title',
            field=models.CharField(blank=True, default='Embed Blogs on Your Website', max_length=100),
        ),
        migrations.AddField(
            model_name='settingspage',
            name='integration_step3_title',
            field=models.CharField(blank=True, default='How It Works', max_length=100),
        ),
    ]
