# Generated by Django 6.0.8 on 2026-10-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_settingspage_integration_page_subtext_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingspage',
            name='manage_users_btn_add_group',
            field=models.CharField(blank=True, default='New Group', max_length=50),
        ),
        migrations.AddField(
            model_name='settingspage',
            name='manage_users_modal_add_group_title',
            field=models.CharField(blank=True, default='Create New Group', max_length=100),
        ),
        migrations.AddField(
            model_name='settingspage',
            name='manage_users_modal_add_user_title',
            field=models.CharField(blank=True, default='Add New Team Member', max_length=100),
        ),
    ]
