# Generated by Django 6.0.8 on 2026-10-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_settingspage_manage_users_btn_add_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdashboardpage',
            name='card_approved_label',
            field=models.CharField(blank=True, default='Approved', max_length=50, verbose_name='Summary Card 3: Approved'),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='card_pending_review_label',
            field=models.CharField(blank=True, default='Pending Review', max_length=50, verbose_name='Summary Card 2: Pending Review'),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='card_rejected_label',
            field=models.CharField(blank=True, default='Rejected', max_length=50, verbose_name='Summary Card 4: Rejected'),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='card_total_comments_label',
            field=models.CharField(blank=True, default='Total Comments', max_length=50, verbose_name='Summary Card 1: Total Comments'),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='filter_blog_label',
            field=models.CharField(blank=True, default='Filter Blog:', max_length=50, verbose_name='Filter Dropdown Label'),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='tab_all_label',
            field=models.CharField(blank=True, default='All', max_length=50, verbose_name='Tab: All'),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='tab_approved_label',
            field=models.CharField(blank=True, default='Approved', max_length=50, verbose_name='Tab: Approved'),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='tab_pending_label',
            field=models.CharField(blank=True, default='Pending', max_length=50, verbose_name='Tab: Pending'),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='tab_rejected_label',
            field=models.CharField(blank=True, default='Rejected', max_length=50, verbose_name='Tab: Rejected'),
        ),
        migrations.AlterField(
            model_name='userdashboardpage',
            name='comments_th_date',
            field=models.CharField(blank=True, default='Date / Time', max_length=50, verbose_name='Column: Date'),
        ),
    ]
