# Generated by Django 6.0.8 on 2026-10-09 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_userdashboardpage_card_approved_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdashboardpage',
            name='action_approve_btn',
            field=models.CharField(blank=True, default='Approve', max_length=50, verbose_name='Action: Approve Button'),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='action_reject_btn',
            field=models.CharField(blank=True, default='Reject', max_length=50, verbose_name='Action: Reject Button'),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='action_reply_btn',
            field=models.CharField(blank=True, default='Reply', max_length=50, verbose_name='Action: Reply Button'),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='all_blog_posts_option',
            field=models.CharField(blank=True, default='All Blog Posts', max_length=50, verbose_name='Dropdown: All Blog Posts Option'),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='blog_selector_label',
            field=models.CharField(blank=True, default='Blog:', max_length=20, verbose_name='Header: Blog Selector Label'),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='bulk_approve_btn',
            field=models.CharField(blank=True, default='Approve', max_length=50, verbose_name='Bulk: Approve Button'),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='bulk_delete_btn',
            field=models.CharField(blank=True, default='Delete Selected', max_length=50, verbose_name='Bulk: Delete Button'),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='bulk_reject_btn',
            field=models.CharField(blank=True, default='Reject', max_length=50, verbose_name='Bulk: Reject Button'),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='comment_subtext_prefix',
            field=models.CharField(blank=True, default='Moderate visitor comments on your blog posts across', max_length=100, verbose_name='Header: Comment Subtext Prefix'),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='delete_modal_cancel_btn',
            field=models.CharField(blank=True, default='Cancel', max_length=50, verbose_name='Delete Modal: Cancel Button'),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='delete_modal_confirm_btn',
            field=models.CharField(blank=True, default='Delete', max_length=50, verbose_name='Delete Modal: Confirm Button'),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='delete_modal_title',
            field=models.CharField(blank=True, default='Delete Comment?', max_length=100, verbose_name='Delete Modal: Title'),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='empty_approved_text',
            field=models.CharField(blank=True, default='No approved comments yet.', max_length=100, verbose_name='Empty State: Approved Tab'),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='empty_spam_text',
            field=models.CharField(blank=True, default='No spam comments. 🎉', max_length=100, verbose_name='Empty State: Spam Tab'),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='reply_modal_cancel_btn',
            field=models.CharField(blank=True, default='Cancel', max_length=50, verbose_name='Reply Modal: Cancel Button'),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='reply_modal_placeholder',
            field=models.CharField(blank=True, default='Write your reply...', max_length=100, verbose_name='Reply Modal: Textarea Placeholder'),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='reply_modal_send_btn',
            field=models.CharField(blank=True, default='Send Reply', max_length=50, verbose_name='Reply Modal: Send Button'),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='reply_modal_their_comment_label',
            field=models.CharField(blank=True, default='Their comment:', max_length=50, verbose_name='Reply Modal: Their Comment Label'),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='reply_modal_your_reply_label',
            field=models.CharField(blank=True, default='Your Reply', max_length=50, verbose_name='Reply Modal: Your Reply Label'),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='status_badge_approved',
            field=models.CharField(blank=True, default='Approved', max_length=50, verbose_name='Badge: Approved'),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='status_badge_pending',
            field=models.CharField(blank=True, default='Pending', max_length=50, verbose_name='Badge: Pending'),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='status_badge_rejected',
            field=models.CharField(blank=True, default='Rejected', max_length=50, verbose_name='Badge: Rejected'),
        ),
        migrations.AddField(
            model_name='userdashboardpage',
            name='team_badge_text',
            field=models.CharField(blank=True, default='Team', max_length=20, verbose_name='Badge: Team'),
        ),
    ]
