# Generated by Django 4.2.11 on 2026-08-09 10:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('website_name', models.CharField(max_length=255, verbose_name='Website Name')),
                ('website_url', models.URLField(max_length=500, verbose_name='Website URL')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='Logo')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('contact_person', models.CharField(max_length=255, verbose_name='Contact Person')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='Status')),
                ('api_key', models.CharField(editable=False, max_length=64, unique=True, verbose_name='API Key')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['-created_at'],
            },
        ),
    ]
