# Generated by Django 6.0.8 on 2026-08-25 12:04

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_platformhomepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyhomepage',
            name='navbar',
            field=wagtail.fields.StreamField([('navbar', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Link Text', 'max_length': 50, 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Use an anchor like #features or a full URL/page path.', 'label': 'Link URL', 'max_length': 255, 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('label', 0), ('link_url', 1)]], {}), 3: ('wagtail.blocks.ListBlock', (2,), {'label': 'Navigation Links', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'default': 'Get Started', 'label': 'Get Started button text', 'max_length': 50, 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'default': '/cms/', 'label': 'Get Started button link', 'max_length': 255, 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('nav_links', 3), ('cta_text', 4), ('cta_link', 5)]], {})}, help_text='Configure the site navigation bar.'),
        ),
        migrations.DeleteModel(
            name='PlatformHomePage',
        ),
    ]
