# Generated by Django 6.0.8 on 2026-08-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0012_alter_companyhomepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyhomepage',
            name='brand_name',
            field=models.CharField(blank=True, help_text="Brand name shown in the navbar/footer (e.g. 'BlogPro').", max_length=100),
        ),
    ]
