# Generated by Django 6.0.8 on 2026-09-07 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0018_companyblogpostspage'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyblogpostspage',
            name='create_button_text',
            field=models.CharField(blank=True, default='Create Blog Post', max_length=100, verbose_name='Create Button Text'),
        ),
        migrations.AddField(
            model_name='companyblogpostspage',
            name='heading',
            field=models.CharField(blank=True, default='Blog Posts', max_length=200, verbose_name='Page Heading'),
        ),
        migrations.AddField(
            model_name='companyblogpostspage',
            name='subtext',
            field=models.CharField(blank=True, default='Manage all blog posts across your workspace', max_length=300, verbose_name='Subtext'),
        ),
    ]
