# Generated by Django 6.0.8 on 2026-09-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0019_companyblogpostspage_create_button_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyblogpostspage',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='companyblogpostspage',
            name='subtext',
        ),
        migrations.AddField(
            model_name='companyblogpostspage',
            name='col_author_label',
            field=models.CharField(blank=True, default='Author', max_length=50),
        ),
        migrations.AddField(
            model_name='companyblogpostspage',
            name='col_status_label',
            field=models.CharField(blank=True, default='Status', max_length=50),
        ),
        migrations.AddField(
            model_name='companyblogpostspage',
            name='col_title_label',
            field=models.CharField(blank=True, default='Title', max_length=50),
        ),
        migrations.AddField(
            model_name='companyblogpostspage',
            name='col_updated_label',
            field=models.CharField(blank=True, default='Last Updated', max_length=50),
        ),
        migrations.AddField(
            model_name='companyblogpostspage',
            name='empty_state_link_text',
            field=models.CharField(blank=True, default='Create your first one', max_length=50),
        ),
        migrations.AddField(
            model_name='companyblogpostspage',
            name='empty_state_text',
            field=models.CharField(blank=True, default='No blog posts yet.', max_length=150),
        ),
        migrations.AddField(
            model_name='companyblogpostspage',
            name='page_heading',
            field=models.CharField(blank=True, default='Blog Posts', max_length=100),
        ),
        migrations.AddField(
            model_name='companyblogpostspage',
            name='page_subtext',
            field=models.CharField(blank=True, default='Manage all blog posts across your workspace', max_length=200),
        ),
        migrations.AlterField(
            model_name='companyblogpostspage',
            name='create_button_text',
            field=models.CharField(blank=True, default='Create Blog Post', max_length=50),
        ),
    ]
