# Generated by Django 6.0.8 on 2026-09-09 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0020_remove_companyblogpostspage_heading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyblogpostspage',
            name='back_button_text',
            field=models.CharField(blank=True, default='Back to Blog Posts', max_length=50),
        ),
        migrations.AddField(
            model_name='companyblogpostspage',
            name='create_heading',
            field=models.CharField(blank=True, default='Create Blog Post', max_length=100),
        ),
        migrations.AddField(
            model_name='companyblogpostspage',
            name='create_subtext',
            field=models.CharField(blank=True, default='Write and publish a new article to your blog', max_length=200),
        ),
        migrations.AddField(
            model_name='companyblogpostspage',
            name='draft_button_text',
            field=models.CharField(blank=True, default='Save as Draft', max_length=50),
        ),
        migrations.AddField(
            model_name='companyblogpostspage',
            name='edit_heading',
            field=models.CharField(blank=True, default='Edit Blog Post', max_length=100),
        ),
        migrations.AddField(
            model_name='companyblogpostspage',
            name='edit_subtext_prefix',
            field=models.CharField(blank=True, default='Update content and settings for', max_length=100),
        ),
        migrations.AddField(
            model_name='companyblogpostspage',
            name='publish_button_text',
            field=models.CharField(blank=True, default='Publish Post', max_length=50),
        ),
        migrations.AddField(
            model_name='companyblogpostspage',
            name='update_button_text',
            field=models.CharField(blank=True, default='Update & Publish', max_length=50),
        ),
    ]
