# Generated by Django 6.0.8 on 2026-09-09 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0021_companyblogpostspage_back_button_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyblogpostspage',
            name='field_body_label',
            field=models.CharField(blank=True, default='Content Body', max_length=100),
        ),
        migrations.AddField(
            model_name='companyblogpostspage',
            name='field_body_placeholder',
            field=models.CharField(blank=True, default='Write your full blog post here...', max_length=200),
        ),
        migrations.AddField(
            model_name='companyblogpostspage',
            name='field_category_label',
            field=models.CharField(blank=True, default='Category', max_length=100),
        ),
        migrations.AddField(
            model_name='companyblogpostspage',
            name='field_category_placeholder',
            field=models.CharField(blank=True, default='Select Category', max_length=100),
        ),
        migrations.AddField(
            model_name='companyblogpostspage',
            name='field_featured_image_label',
            field=models.CharField(blank=True, default='Featured Image', max_length=100),
        ),
        migrations.AddField(
            model_name='companyblogpostspage',
            name='field_short_desc_label',
            field=models.CharField(blank=True, default='Short Description / Subtitle', max_length=100),
        ),
        migrations.AddField(
            model_name='companyblogpostspage',
            name='field_short_desc_placeholder',
            field=models.CharField(blank=True, default='Brief summary of your article...', max_length=200),
        ),
        migrations.AddField(
            model_name='companyblogpostspage',
            name='field_title_label',
            field=models.CharField(blank=True, default='Blog Title', max_length=100),
        ),
        migrations.AddField(
            model_name='companyblogpostspage',
            name='field_title_placeholder',
            field=models.CharField(blank=True, default='e.g. 10 Tips for Better Web Performance', max_length=200),
        ),
    ]
