# Generated by Django 6.0.8 on 2026-09-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0023_alter_companyhomepage_body_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Approval Status'),
        ),
    ]
