# Generated by Django 6.0.8 on 2026-10-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0024_company_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='allow_comments',
            field=models.BooleanField(default=True, verbose_name='Allow Comments Globally'),
        ),
    ]
