# Generated by Django 6.0.8 on 2026-10-07 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0025_company_allow_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='comments_allow_replies',
            field=models.BooleanField(default=True, verbose_name='Allow Comment Replies'),
        ),
        migrations.AddField(
            model_name='company',
            name='comments_email_field_mode',
            field=models.CharField(choices=[('required', 'Required'), ('optional', 'Optional'), ('hidden', 'Hidden / Disabled')], default='optional', max_length=20, verbose_name='Email Field Mode'),
        ),
        migrations.AddField(
            model_name='company',
            name='comments_name_field_required',
            field=models.BooleanField(default=True, verbose_name='Name Field Required'),
        ),
        migrations.AddField(
            model_name='company',
            name='comments_per_page',
            field=models.PositiveIntegerField(default=10, verbose_name='Comments Per Page'),
        ),
        migrations.AddField(
            model_name='company',
            name='comments_require_moderation',
            field=models.BooleanField(default=True, verbose_name='Review All Comments'),
        ),
        migrations.AddField(
            model_name='company',
            name='comments_under_review_message',
            field=models.CharField(default='Your comment has been submitted and is awaiting approval.', max_length=255, verbose_name='Under-review Message'),
        ),
    ]
