# Generated by Django 6.0.8 on 2026-10-07 11:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0026_company_comments_allow_replies_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Group Name')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='Description')),
                ('can_create_posts', models.BooleanField(default=True, verbose_name='Can Create Posts')),
                ('can_edit_posts', models.BooleanField(default=True, verbose_name='Can Edit Posts')),
                ('can_publish_posts', models.BooleanField(default=False, verbose_name='Can Publish Posts')),
                ('can_manage_comments', models.BooleanField(default=False, verbose_name='Can Manage Comments')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_groups', to='companies.company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'User Group',
                'verbose_name_plural': 'User Groups',
                'ordering': ['name'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.AddField(
            model_name='companymembership',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='companies.usergroup', verbose_name='User Group'),
        ),
    ]
