# Generated by Django 6.0.8 on 2026-10-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0027_usergroup_companymembership_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyblogpostspage',
            name='approve_btn_text',
            field=models.CharField(blank=True, default='Approve', max_length=50),
        ),
        migrations.AddField(
            model_name='companyblogpostspage',
            name='publish_box_header',
            field=models.CharField(blank=True, default='Publish', max_length=50),
        ),
        migrations.AddField(
            model_name='companyblogpostspage',
            name='reject_btn_text',
            field=models.CharField(blank=True, default='Reject', max_length=50),
        ),
        migrations.AddField(
            model_name='companyblogpostspage',
            name='status_label',
            field=models.CharField(blank=True, default='Status:', max_length=50),
        ),
        migrations.AddField(
            model_name='companyblogpostspage',
            name='status_value_text',
            field=models.CharField(blank=True, default='Draft / Published', max_length=50),
        ),
        migrations.AddField(
            model_name='companyblogpostspage',
            name='visibility_label',
            field=models.CharField(blank=True, default='Visibility:', max_length=50),
        ),
        migrations.AddField(
            model_name='companyblogpostspage',
            name='visibility_value_text',
            field=models.CharField(blank=True, default='Public', max_length=50),
        ),
    ]
