# Generated by Django 6.0.8 on 2026-08-14 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
        ('companies', '0004_company_domain_company_slug_companymembership'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpage',
            options={'verbose_name': 'Blog', 'verbose_name_plural': 'Blogs'},
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='status',
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='companies.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='blogtag',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='companies.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='slug',
            field=models.SlugField(max_length=100, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Derived automatically from the parent page.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='blogs', to='companies.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='blogtag',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='blogtag',
            name='slug',
            field=models.SlugField(max_length=100, verbose_name='Slug'),
        ),
        migrations.AlterUniqueTogether(
            name='blogcategory',
            unique_together={('company', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='blogtag',
            unique_together={('company', 'slug')},
        ),
    ]
