# Generated by Django 6.0.8 on 2026-08-14 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_blogpage_options_remove_blogpage_status_and_more'),
        ('companies', '0004_company_domain_company_slug_companymembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategory',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='companies.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='blogtag',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='companies.company', verbose_name='Company'),
        ),
    ]
