# Generated by Django 6.0.8 on 2026-08-14 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blogcategory_company_alter_blogtag_company'),
        ('companies', '0004_company_domain_company_slug_companymembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategory',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='companies.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='blogtag',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='companies.company', verbose_name='Company'),
        ),
    ]
