# Generated by Django 6.0.8 on 2026-09-09 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_blogcategory_company_alter_blogtag_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='empty_state_text',
            field=models.CharField(default='No blog posts published yet.', help_text='Text shown when there are no published blogs', max_length=255),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='read_more_text',
            field=models.CharField(default='Read Article', help_text='Text for the button on each blog card', max_length=50),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='subtitle',
            field=models.CharField(blank=True, default='Explore our latest blog posts and articles.', help_text='Subtitle shown under the main title on blog listing page', max_length=255),
        ),
    ]
