# Generated by Django 6.0.8 on 2026-09-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_blogindexpage_empty_state_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='short_description',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Short Description'),
        ),
    ]
