# Generated by Django 6.0.8 on 2026-09-25 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_alter_blogpage_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Waiting for Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=20, verbose_name='Approval Status'),
        ),
    ]
