# Generated by Django 6.0.8 on 2026-10-05 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_alter_blogcomment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='allow_comments',
            field=models.BooleanField(default=True, help_text='Enable or disable visitor comments for this blog post.', verbose_name='Allow Comments'),
        ),
    ]
